const $ = id => document.getElementById(id);
let state = {settings:{}, users:[], keys:[]};
async function api(action, extra={}){const r=await fetch('/api/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({success:false,msg:'Invalid server response'}));if(r.status===401){showLogin();throw new Error(d.msg||'Unauthorized')}return d}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),2500)}
function showLogin(){$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function fmtDate(v){if(!v)return 'Permanent';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function inputDate(v){if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function load(){const d=await api('get_all_data');if(!d.success)throw new Error(d.msg||'Failed');state=d;render();showApp()}
function render(){const s=state.settings||{};$('statUsers').textContent=state.users.length;$('statKeys').textContent=state.keys.length;$('statActive').textContent=state.users.filter(u=>['active','enabled'].includes(String(u.status).toLowerCase())).length;$('statRecharge').textContent='₹'+Number(s.minRecharge||0).toLocaleString('en-IN');
['appName','logoUrl','registerUrl','rechargeUrl','referralCode','telegramSupport','telegramUsername','broadcastMessage','minRecharge','previewLossCount'].forEach(id=>{if($(id))$(id).value=s[id]??''});
$('usersTable').innerHTML=state.users.map(u=>`<tr><td class="font-mono font-bold">${esc(u.uid)}</td><td>${esc(u.plan)}</td><td>₹${Number(u.todayRecharge||0).toLocaleString('en-IN')}</td><td>${esc(fmtDate(u.expiresAt))}</td><td><span class="tag ${u.status==='active'?'active':'disabled'}">${esc(u.status||'active')}</span></td><td class="font-mono text-xs">${esc(u.hwid||'—')}</td><td><button class="btn text-xs border border-white/10 mr-1" onclick="editUid('${esc(u.uid)}')">Edit</button><button class="btn text-xs danger mr-1" onclick="resetHwid('${esc(u.uid)}')">Reset HWID</button><button class="btn text-xs danger" onclick="deleteUid('${esc(u.uid)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7" class="text-center muted py-6">No UIDs yet</td></tr>';
$('keysTable').innerHTML=state.keys.map(k=>`<tr><td class="font-mono font-bold">${esc(k.key)}</td><td>${esc(k.plan)}</td><td>${esc(fmtDate(k.expiresAt))}</td><td><span class="tag ${k.status==='active'?'active':'disabled'}">${esc(k.status||'active')}</span></td><td class="font-mono text-xs">${esc(k.hwid||'—')}</td><td><button class="btn text-xs border border-white/10 mr-1" onclick="editKey('${esc(k.key)}')">Edit</button><button class="btn text-xs danger" onclick="deleteKey('${esc(k.key)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="text-center muted py-6">No keys yet</td></tr>'}
async function saveSettings(){const settings={appName:$('appName').value.trim(),logoUrl:$('logoUrl').value.trim(),registerUrl:$('registerUrl').value.trim(),rechargeUrl:$('rechargeUrl').value.trim(),referralCode:$('referralCode').value.trim(),telegramSupport:$('telegramSupport').value.trim(),telegramUsername:$('telegramUsername').value.trim(),broadcastMessage:$('broadcastMessage').value.trim(),minRecharge:Number($('minRecharge').value||0),previewLossCount:Number($('previewLossCount').value||1)};const d=await api('save_settings',{settings});if(!d.success)throw new Error(d.msg);state.settings=d.settings;render();toast('Settings saved')}
function clearUid(){$('uidMode').value='add';$('uidForm').reset();$('uidActive').checked=true;$('uidPlan').value='VIP';$('uidRecharge').value=0}
function clearKey(){$('keyMode').value='add';$('keyForm').reset();$('keyActive').checked=true;$('keyUid').value='KEY';$('keyPlan').value='VIP KEY'}
async function submitUid(e){e.preventDefault();const action=$('uidMode').value==='edit'?'update_uid':'add_uid';const d=await api(action,{uid:$('uid').value,plan:$('uidPlan').value,expiresAt:$('uidExpiry').value,todayRecharge:Number($('uidRecharge').value||0),hwid:$('uidHwid').value,notes:$('uidNotes').value,active:$('uidActive').checked});if(!d.success)throw new Error(d.msg);clearUid();await load();toast('UID saved')}
async function submitKey(e){e.preventDefault();const action=$('keyMode').value==='edit'?'update_key':'add_key';const d=await api(action,{key:$('key').value,uid:$('keyUid').value,plan:$('keyPlan').value,expiresAt:$('keyExpiry').value,hwid:$('keyHwid').value,active:$('keyActive').checked});if(!d.success)throw new Error(d.msg);clearKey();await load();toast('Key saved')}
window.editUid=function(uid){const u=state.users.find(x=>String(x.uid)===String(uid));if(!u)return;$('uidMode').value='edit';$('uid').value=u.uid;$('uidPlan').value=u.plan||'VIP';$('uidExpiry').value=inputDate(u.expiresAt);$('uidRecharge').value=u.todayRecharge||0;$('uidHwid').value=u.hwid||'';$('uidNotes').value=u.notes||'';$('uidActive').checked=u.status!=='disabled';window.scrollTo({top:document.querySelector('#uidForm').getBoundingClientRect().top+scrollY-80,behavior:'smooth'})}
window.editKey=function(key){const k=state.keys.find(x=>String(x.key).toUpperCase()===String(key).toUpperCase());if(!k)return;$('keyMode').value='edit';$('key').value=k.key;$('keyUid').value=k.uid||'KEY';$('keyPlan').value=k.plan||'VIP KEY';$('keyExpiry').value=inputDate(k.expiresAt);$('keyHwid').value=k.hwid||'';$('keyActive').checked=k.status!=='disabled';window.scrollTo({top:document.querySelector('#keyForm').getBoundingClientRect().top+scrollY-80,behavior:'smooth'})}
window.deleteUid=async uid=>{if(!confirm('Delete UID '+uid+'?'))return;const d=await api('delete_uid',{uid});if(!d.success)throw new Error(d.msg);await load();toast('UID deleted')}
window.resetHwid=async uid=>{if(!confirm('Reset HWID for '+uid+'?'))return;const d=await api('reset_hwid',{uid});if(!d.success)throw new Error(d.msg);await load();toast('HWID reset')}
window.deleteKey=async key=>{if(!confirm('Delete key '+key+'?'))return;const d=await api('delete_key',{key});if(!d.success)throw new Error(d.msg);await load();toast('Key deleted')}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='';try{const d=await api('admin_login',{password:$('password').value});if(!d.success)throw new Error(d.msg);await load()}catch(err){$('loginMsg').textContent=err.message}});
$('logout').onclick=async()=>{await api('admin_logout');showLogin()};$('saveSettings').onclick=()=>saveSettings().catch(e=>toast(e.message));$('uidForm').onsubmit=e=>submitUid(e).catch(x=>toast(x.message));$('keyForm').onsubmit=e=>submitKey(e).catch(x=>toast(x.message));$('uidClear').onclick=clearUid;$('keyClear').onclick=clearKey;$('refresh').onclick=()=>load().catch(e=>toast(e.message));
load().catch(()=>showLogin());
